import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components1/smallComponents/Header";
import Section5 from "../components1/smallComponents/Footer2";
import Section6 from "../components1/smallComponents/Footer";
import BreadCrumb from "../components1/smallComponents/BreadCrumb";
import { Toaster } from "@/components/ui/toaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <BreadCrumb />
        <main>{children}</main>
        <Toaster />
        <Section5 />
        <Section6 />
      </body>
    </html>
  );
}
